-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9VFdcGoT0YHKjKaW
S+HHtTgKHXIT3Bw7dHpfEPJ5qXOgCgYIKoZIzj0DAQehRANCAATIEE8fbYM/BmXm
GUORW7P6/NfI3cpkyXo2NzHT5LdSXQ7eNPeJ05o1zKiUyi2FcQK9bcmclbe0LOUo
YCmyNRnV
-----END PRIVATE KEY-----