# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "DemoCICDiOS",
      devices: ["iPhone 16 Pro"],
      clean: true,
      output_directory: "./fastlane/test_output"
    )
  end

  desc "Build the app"
  lane :build do
    gym(
      scheme: "DemoCICDiOS",
      export_method: "ad-hoc"
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      scheme: "DemoCICDiOS"
    )
    upload_to_testflight
  end
  
end
